### ISSUE TITLE
JSONRenderer shall produce one-line JSON document. Do not pretty print.

### ISSUE THREAD

**Issue by vlcinsky** [tyler46/nameko-structlog#3]
https://github.com/tyler46/nameko-structlog/blob/master/nameko_structlog/nameko_structlog.py#L54 is passing `indent=2` so the log record is pretty printed.

This makes processing of log record difficult, e.g. fluentd is confused by having JSON on multiple lines, it also increases size of log records.

Better omit the `indent` argument to produce JSON document fitting one line.

**Comment by tyler46** [comment]
@vlcinsky thank you for your report. I think you are right, I am going to reactor a bit how structlog gets configured and I will fix this issue too.

**Comment by tyler46** [comment]
@vlcinsky will push a new release within this week.

**Comment by tyler46** [comment]
@vlcinsky sorry for my slow reply on this. A new version has been [released](https://pypi.org/project/nameko-structlog/).
